language: php
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - vendor
  - $HOME/.composer

php:
  - "5.5"
  - "5.6"
  - "7.0"

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
